apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx123
  name: nginx123
spec:
  containers:
  - image: nginx
    name: nginx123
    ports:
      - containerPort: 80
        name: my-service
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: mypd
  volumes:
  - name: mypd
    persistentVolumeClaim:
      claimName: mypvc
