apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis123
  name: redis123
spec:
  containers:
  - image: redis
    name: redis123
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: cache-volume
    emptyDir:
      sizeLimit: 500Mi
status: {}
