apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx7
  name: nginx7
spec:
  containers:
  - image: nginx
    name: nginx7
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeSelector:
    nodeName: nginxnode
status: {}
